### ISSUE TITLE
fusioncharts error

### ISSUE THREAD

**Issue by amolngt** [fusioncharts/django-wrapper#4]
(index):25 Uncaught ReferenceError: FusionCharts is not defined
    at (index):25
(anonymous) @ (index):25
(index):30 Uncaught ReferenceError: FusionCharts is not defined
    at (index):30

m getting this error

thanks in advance

**Comment by bdallard** [comment]
Same error... 
Thanks in advance !

**Comment by suvradip** [comment]
Thanks for your feedback. Have you included the FusionCharts js lib as the static files in the project? 
_FusionCharts is not defined_ this error is coming in browser's console because of that. 
If you have that error after adding fusionchart js lib as static files in project then please share your sample for further debugging.

You can dowload FusionCharts lib from [here](https://www.fusioncharts.com/download/)

**Comment by bdallard** [comment]
First, thanks for your quick response !
I have download the FusionCharts lib, I have indeed a folder with multiple js files such as fusioncharts.js, fusioncharts.theme.fint.js ... 
So I inserted those file in Project/fusioncharts/templates/static/
, but I have a new error : chart type not supported. 
& Console ==> "Failed to load resource: the server responded with a status of 404 (Not Found)" 
What can I do ?

**Comment by ayanbhaduryfc** [comment]
@bdallard Please drop a mail to support@fusioncharts.com, we would assist you accordingly.

**Comment by bdallard** [comment]
Done. 
Thanks in advance

**Comment by ayanbhaduryfc** [comment]
@bdallard Okay, thanks, meanwhile you can check this blog post link - https://www.fusioncharts.com/blog/creating-charts-in-django/
